.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WALK" "1" "January 2017" "" ""
.
.SH "NAME"
\fBwalk\fR \- A fast, lightweight, general purpose build and task execution utility\.
.
.SH "SYNOPSIS"
\fBwalk\fR \fB\-\-version\fR
.
.br
\fBwalk\fR [target]
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-v\fR Show stdout from rules when executing the \fBexec\fR phase\.
.
.IP "\(bu" 4
\fB\-p\fR Only plan the execution and print the graph\. Does not execute the \fBexec\fR phase\.
.
.IP "" 0
.
.SH "BUGS"
You can find a list of bugs at https://github\.com/ejholmes/walk/issues\. Please report any issues there\.
.
.SH "COPYRIGHT"
Walk is Copyright (C) 2017 Eric Holmes
.
.SH "SEE ALSO"
make(1), bash(1)
