#!/bin/bash

phase=$1
target=$2

case $target in
  all)
    case $phase in
      deps)
        echo walk.1
        echo walk.1.html
        ;;
    esac ;;

  walk.1)
    case $phase in
      deps)
        echo "$target".md
        echo ../bundled
        ;;
      exec)
        cp "$target".md "$target".ronn
        exec bundle exec ronn "$target".ronn
        ;;
    esac ;;

  walk.1.html)
    case $phase in
      # Building walk.1 with ronn implicitly builds walk.1.html
      deps) echo ${target%.html} ;;
    esac
esac
