#!/bin/bash

phase=$1
target=$2

case $target in
  all)
    case $phase in
      deps) echo integration ;;
    esac ;;

  clean)
    case $phase in
      deps)
        echo 111-compile/clean
        echo 110-compile/clean
        echo 200-frontend/clean
        ;;
    esac ;;

  bundled)
    case $phase in
      deps) echo ../bundled ;;
    esac ;;

  integration)
    case $phase in
      deps)
        echo ../bundled
        echo 110-compile/all
        echo 111-compile/all
        echo 200-frontend/all
        echo 300-docker/all
        ;;
    esac ;;

  unit)
    case $phase in
      deps) echo ../src ;;
      exec) exec go test -race ../...
    esac ;;

  # Generic rule: compile any .c file to .o
  # This is inherited by subdirectories via exit 200
  */*.o)
    src=${target%.o}.c
    case $phase in
      deps) echo $src ;;
      exec) exec gcc -Wall -o $target -c $src ;;
    esac ;;

  # Static files - no build needed
  */*.c|*/*.h) ;;

  *) >&2 echo "No rule for target \"$target\"" && exit 1 ;;
esac
