#!/bin/bash

phase=$1
target=$2

clean() {
  rm -rf *.o hello
}

case $target in
  all)
    case $phase in
      deps)
        # Absolute paths work too.
        echo $PWD/hello
        echo test
        ;;
    esac ;;

  clean)
    case $phase in
      exec) clean ;;
    esac ;;

  test) ;; # phony target

  hello)
    case $phase in
      deps) echo hello.o ;;
      exec) exec gcc -Wall -o hello $($0 deps $target) ;;
    esac ;;

  # Delegate unknown targets (like *.o) to parent Walkfile
  *) exit 200 ;;
esac
