.\" Manpage for walk.
.\" Contact eric@ejholmes.net to correct errors or typos.
.TH man 1 "04 Jan 2017" "1.0" "walk man page"
.SH NAME
walk - Walk a directed acyclic graph of executables
.SH SYNOPSIS
\fBwalk\fR \fB\-\-version\fR
.
.br
\fBwalk\fR \fI[target]\fR [\fB\fB\-v\fR] \.\.\.
.SH DESCRIPTION
Walk is a lightweight utility for building and executing directed acyclic graphs that are represented as executables on a file system.
.SH OPTIONS
The walk does not take any options. However, you can supply username.
.SH SEE ALSO
make(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Eric Holmes (eric@ejholmes.net)
