#!/bin/bash

phase=$1
target=$2

install() {
  exec go install .
}

case $target in
  all)
    case $phase in
      deps) 
        echo bin
        echo test
        echo install
        echo docs
        ;;
    esac ;;

  clean)
    case $phase in
      deps)
        echo test/clean
        echo bin/clean
        ;;
    esac ;;

  install)
    case $phase in
      deps) echo src ;;
      exec) install ;;
    esac ;;

  release|version.go) exec ./.walk/$target $@ ;;

  bin|test|docs|man)
    case $phase in
      deps) echo $target/all ;;
    esac ;;

  src)
    case $phase in
      deps) ls *.go | grep -v _test ;;
    esac ;;

  error)
    case $phase in
      deps) echo test/000-cancel/fail ;;
    esac ;;
esac
