#!/bin/bash

phase=$1
target=$2

case $target in
  all)
    case $phase in
      deps) echo a ;;
    esac ;;

  a)
    case $phase in
      deps) echo b ;;
    esac ;;

  b)
    case $phase in
      deps) echo a ;;
    esac ;;
esac
