name: CI

on:
  push:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'
      - run: devbox install
      - run: devbox run go install .
      - run: devbox run walk -v test/unit

  integration:
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=mod
    steps:
      - uses: actions/checkout@v4
      - uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'
      - run: devbox install
      - run: devbox run go install .
      - run: devbox run walk -v test/integration
